sudoku_alldifferent_sudoku_p18 = ["models/sudoku/sudoku_alldifferent_sudoku_p18.fzn"]
sudoku_alldifferent_sudoku_p4 = ["models/sudoku/sudoku_alldifferent_sudoku_p4.fzn"]
sudoku_alldifferent_sudoku_p11 = ["models/sudoku/sudoku_alldifferent_sudoku_p11.fzn"]
sudoku_alldifferent_sudoku_p9 = ["models/sudoku/sudoku_alldifferent_sudoku_p9.fzn"]
sudoku_alldifferent_sudoku_p16 = ["models/sudoku/sudoku_alldifferent_sudoku_p16.fzn"]
sudoku_alldifferent_sudoku_p12 = ["models/sudoku/sudoku_alldifferent_sudoku_p12.fzn"]
sudoku_alldifferent_sudoku_p13 = ["models/sudoku/sudoku_alldifferent_sudoku_p13.fzn"]
sudoku_alldifferent_sudoku_p17 = ["models/sudoku/sudoku_alldifferent_sudoku_p17.fzn"]
sudoku_alldifferent_sudoku_p20 = ["models/sudoku/sudoku_alldifferent_sudoku_p20.fzn"]
sudoku_alldifferent_sudoku_p19 = ["models/sudoku/sudoku_alldifferent_sudoku_p19.fzn"]
sudoku_alldifferent_sudoku_p8 = ["models/sudoku/sudoku_alldifferent_sudoku_p8.fzn"]
sudoku_alldifferent_sudoku_p3 = ["models/sudoku/sudoku_alldifferent_sudoku_p3.fzn"]
sudoku_alldifferent_sudoku_p15 = ["models/sudoku/sudoku_alldifferent_sudoku_p15.fzn"]
sudoku_alldifferent_sudoku_p14 = ["models/sudoku/sudoku_alldifferent_sudoku_p14.fzn"]
sudoku_alldifferent_sudoku_p7 = ["models/sudoku/sudoku_alldifferent_sudoku_p7.fzn"]
sudoku_alldifferent_sudoku_p6 = ["models/sudoku/sudoku_alldifferent_sudoku_p6.fzn"]
sudoku_alldifferent_sudoku_p0 = ["models/sudoku/sudoku_alldifferent_sudoku_p0.fzn"]
sudoku_alldifferent_sudoku_p2 = ["models/sudoku/sudoku_alldifferent_sudoku_p2.fzn"]
sudoku_alldifferent_sudoku_p1 = ["models/sudoku/sudoku_alldifferent_sudoku_p1.fzn"]
sudoku_alldifferent_sudoku_p10 = ["models/sudoku/sudoku_alldifferent_sudoku_p10.fzn"]
