tsp_TSP_N5_1 = ["models/tsp/tsp_TSP_N5_1.fzn"]
tsp_TSP_N5_4 = ["models/tsp/tsp_TSP_N5_4.fzn"]
tsp_TSP_N10_4 = ["models/tsp/tsp_TSP_N10_4.fzn"]
tsp_TSP_N10_1 = ["models/tsp/tsp_TSP_N10_1.fzn"]
tsp_TSP_N5_3 = ["models/tsp/tsp_TSP_N5_3.fzn"]
tsp_TSP_N15_3 = ["models/tsp/tsp_TSP_N15_3.fzn"]
tsp_TSP_N5_2 = ["models/tsp/tsp_TSP_N5_2.fzn"]
tsp_TSP_N10_0 = ["models/tsp/tsp_TSP_N10_0.fzn"]
tsp_TSP_N20_1 = ["models/tsp/tsp_TSP_N20_1.fzn"]
tsp_TSP_N20_0 = ["models/tsp/tsp_TSP_N20_0.fzn"]
tsp_TSP_N20_3 = ["models/tsp/tsp_TSP_N20_3.fzn"]
tsp_TSP_N15_1 = ["models/tsp/tsp_TSP_N15_1.fzn"]
tsp_TSP_N20_4 = ["models/tsp/tsp_TSP_N20_4.fzn"]
tsp_TSP_N15_2 = ["models/tsp/tsp_TSP_N15_2.fzn"]
tsp_TSP_N15_4 = ["models/tsp/tsp_TSP_N15_4.fzn"]
tsp_TSP_N5_0 = ["models/tsp/tsp_TSP_N5_0.fzn"]
tsp_TSP_N20_2 = ["models/tsp/tsp_TSP_N20_2.fzn"]
tsp_TSP_N15_0 = ["models/tsp/tsp_TSP_N15_0.fzn"]
tsp_TSP_N10_3 = ["models/tsp/tsp_TSP_N10_3.fzn"]
tsp_TSP_N10_2 = ["models/tsp/tsp_TSP_N10_2.fzn"]
